/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: wallmasterr (https://sketchfab.com/wallmasterr)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/tenhun-falling-spaceman-fanart-9fd80b6a259f41fd99e6f56eee686dc5
Title: Tenhun Falling spaceman (FanArt)
*/

import React, { useRef,useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useFrame } from "@react-three/fiber";

export function Astronaut(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/tenhun_falling_spaceman_fanart.glb')
  // Refs for both thighs
  const thighL = useRef();
  const thighR = useRef();
  const spine = useRef();
  const head = useRef();

  

  // 🧩 Grab the bones by name after loading
  useEffect(() => {
    nodes.metarig_rootJoint.traverse((obj) => {
      if (obj.isBone) {
        if (obj.name === "thighL_metarig") thighL.current = obj;
        if (obj.name === "thighR_metarig") thighR.current = obj;
        if (obj.name === "spine003_metarig") spine.current = obj;
        if (obj.isBone && obj.name.toLowerCase().includes("head")) {
          head.current = obj;
        }
      }
    });
  }, [nodes]);

  useEffect(() => {
    if (spine.current) {
      spine.current.rotation.x = 0.3; // ~17° forward
    }

    if (head.current) {
     // Tilt head backward by ~25–30 degrees
      head.current.rotateX(-Math.PI / 7) // ~-25.7° backward
    }
  }, []);


  // 🌀 Animate the thigh bend (as if falling)
  useFrame((state) => {
    const t = state.clock.elapsedTime;
    if (thighL.current) thighL.current.rotation.x = Math.sin(t) * 0.2;
    if (thighR.current) thighR.current.rotation.x = Math.sin(t + Math.PI / 3) * 0.2;
    
    if (head.current) {
    head.current.rotation.x = -Math.PI / 7 + Math.sin(t * 0.5) * 0.05;
    head.current.rotation.z = Math.sin(t * 0.3) * 0.05;
  }


  });
   

  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[Math.PI /2, -0.7, 4.75]} scale={0.193}>
          <group name="Root">
            <group name="metarig">
              <primitive object={nodes.metarig_rootJoint} />
              <skinnedMesh
                name="Cube001_0"
                geometry={nodes.Cube001_0.geometry}
                material={materials['AstronautFallingTexture.png']}
                skeleton={nodes.Cube001_0.skeleton}
              />
              <skinnedMesh
                name="Cube005_0"
                geometry={nodes.Cube005_0.geometry}
                material={materials['AstronautFallingTexture.png']}
                skeleton={nodes.Cube005_0.skeleton}
              />
              <skinnedMesh
                name="Cube002_0"
                geometry={nodes.Cube002_0.geometry}
                material={materials['AstronautFallingTexture.png']}
                skeleton={nodes.Cube002_0.skeleton}
              />
              <skinnedMesh
                name="Plane_0"
                geometry={nodes.Plane_0.geometry}
                material={materials['AstronautFallingTexture.png']}
                skeleton={nodes.Plane_0.skeleton}
              />
              <skinnedMesh
                name="Cube008_0"
                geometry={nodes.Cube008_0.geometry}
                material={materials['AstronautFallingTexture.png']}
                skeleton={nodes.Cube008_0.skeleton}
              />
              <skinnedMesh
                name="Cube004_0"
                geometry={nodes.Cube004_0.geometry}
                material={materials['AstronautFallingTexture.png']}
                skeleton={nodes.Cube004_0.skeleton}
              />
              <skinnedMesh
                name="Cube003_0"
                geometry={nodes.Cube003_0.geometry}
                material={materials['AstronautFallingTexture.png']}
                skeleton={nodes.Cube003_0.skeleton}
              />
              <skinnedMesh
                name="Cube_0"
                geometry={nodes.Cube_0.geometry}
                material={materials['AstronautFallingTexture.png']}
                skeleton={nodes.Cube_0.skeleton}
              />
              <skinnedMesh
                name="Cube009_0"
                geometry={nodes.Cube009_0.geometry}
                material={materials['AstronautFallingTexture.png']}
                skeleton={nodes.Cube009_0.skeleton}
              />
              <skinnedMesh
                name="Cube011_0"
                geometry={nodes.Cube011_0.geometry}
                material={materials['AstronautFallingTexture.png']}
                skeleton={nodes.Cube011_0.skeleton}
              />
              <group name="Cube001" />
              <group name="Cube005" />
              <group name="Cube002" />
              <group name="Plane" />
              <group name="Cube008" />
              <group name="Cube004" />
              <group name="Cube003" />
              <group name="Cube" />
              <group name="Cube009" rotation={[-2.708, 0.013, -1.447]} scale={1.307} />
              <group name="Cube011" />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/tenhun_falling_spaceman_fanart.glb')
